[package]
name = "rcp_batch"
type = "bin"
authors = ["rymnc <43716372+rymnc@users.noreply.github.com>"]
compiler_version = ">=1.0.0"

[dependencies]
rcp_lib = { path = "../lib" }
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v5.0.0-nightly.20260324", directory = "barretenberg/noir/bb_proof_verification" }
