[31337]
endpoint_url = "http://localhost:8545"

[31337.bool]
use_mock_verifier = "${USE_MOCK_VERIFIER}"

[31337.address]
governance = "${GOVERNANCE}"
multisig = "${MULTISIG}"
guardian = "${GUARDIAN}"
identity_tree_address = "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
enrollment_address = "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853"
identity_verifier_address = "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6"
enrollment_verifier_address = "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"
membership_verifier_address = "0x0165878A594ca255338adfa4d48449f69242Eb8F"

[11155111]
endpoint_url = "${SEPOLIA_RPC_URL}"

[11155111.bool]
use_mock_verifier = "${USE_MOCK_VERIFIER}"

[11155111.address]
governance = "${GOVERNANCE}"
multisig = "${MULTISIG}"
guardian = "${GUARDIAN}"
enrollment_verifier_address = "${ENROLLMENT_VERIFIER_ADDRESS}"
membership_verifier_address = "${MEMBERSHIP_VERIFIER_ADDRESS}"
